# Website settings
title: "Nelson Madubuonwu"
keywords: "Nelson,Madubuonwu,product,manager,apparel,Bonobos,personal,portfolio"
baseurl: "/"
url: "http://nelson-madu.github.io"
favicon: "static/img/favicon.ico?v=2"
# url: "http://127.0.0.1:4000"

author:
  name: " "
  email: 'nelsonmadubuonwu@aya.yale.edu' 
  linkedin: 'https://www.linkedin.com/in/nmadubuonwu'
  head_img: 'static/img/landing/Nelson.jpg'
  tag: 'Product Manager'
  desc: > 
            <br />
            Apparel product manager <a href="http://www.bonobos.com/">@BONOBOS</a>, a digitally native, vertically integrated menswear brand. 
            <br />Defining the landscape of men's e-commers by shipping great fit and excellent customer service.
            
stylesheets:
  - url: "lib/css/bootstrap.min.css"
  - url: "lib/css/animate.min.css"
  - url: "static/css/style.min.css"

scripts:
  - url: "lib/js/jquery.min.js"
  - url: "lib/js/wow.min.js"
  - url: "lib/js/pace.min.js"
  - url: "lib/js/bootstrap.min.js"

sections:
  - id: "about"
    name: "About"
    tpl: "about.html"
  - id: "career"
    name: "Career"
    tpl: "timeline.html"
  - id: "projects"
    name: "Projects"
    tpl: "projects.html"
  - id: 'links' 
    name: 'Contact'
    tpl: 'links.html'
    css: 'contact'
 
# Build settings
encoding: "utf-8"


# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
